# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='CGV',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='ENV',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='QUAL',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='SOC',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='nation',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
    ]
