# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agcs', '0003_auto_20170919_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='years',
            old_name='name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='years',
            name='ESG',
            field=models.CharField(default='NA', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='years',
            name='year',
            field=models.CharField(default='NA', max_length=4),
            preserve_default=False,
        ),
    ]
